### ISSUE TITLE
dlopen error in meshing

### ISSUE THREAD

**Issue by hpjeonGIT** [fireFoam-dev/fireFoam-dev#4]
Hi,

I compiled firefoam-dev and openfoam-dev using the exact branch mentioned in the repository. Compilation yielded no error message but when I tried cases (fireFoam-dev/cases/singleBox), they yield following messages:

log.blockMesh:26:    dlopen error : /home/jeonb/OpenFOAM/jeonb-dev_FF/platforms/linux64IccDPInt32Opt/lib/libfvPatchFieldsPyrolysis.so: undefined symbol: _ZTIN4Foam11solidThermoE

I confirmed that all libraries are in LD_LIBRARY_PATH but not sure why it produces such an error message. They are compiled using intel compiler/mpi 2018 on CENTOS6.3. Any comments are appreciated.

Best regards,

Byoungseon

**Comment by karlvirgil** [comment]
I've just updated the cases now.  Please pull again (and update to OpenFOAM-dev commit 940e28f63681c7e5b292096d8fd35a71acd52599) and all should work.

**Comment by hpjeonGIT** [comment]
Thanks for the update. We just checked that most of examples work great, including mpirun tests. 

Best regards,

Byoungseon
